# Generated by Django 3.0.5 on 2020-05-18 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sopumshop', '0002_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='picture',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
